# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

permalink: /:categories/:title/

# Site settings
title: "Time and thoughts"
description: ''
baseurl: ''
url: "https://maheshm.co.in" # the base hostname & protocol for your site
email: 'maheshmukundan@gmail.com'
author: 'Mahesh M'

twitter_username: freemahesh
github_username: maheshm

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Build settings
markdown: kramdown
highlighter: rouge

# For sitemap
url: "http://maheshm.co.in" # the base hostname & protocol for your site
